### ISSUE TITLE
Missing build-dependency on libcleri-dev

### ISSUE THREAD

**Issue by Svedrin** [SiriDB/siridb-server#105]
The debs are missing a build-dependency on libcleri-dev.

**Comment by Svedrin** [comment]
(probably irrelevant now that #107 has been merged.)

**Comment by joente** [comment]
In the old days `libcleri` was part of the SiriDB server code. It is only later that we deployed this as a separate library. This means the deb package will only work on recent Debian systems. (It is for example part of Ubuntu since 18.04). I think we can close this issue if we are fine with supporting only new distro's, otherwise we have to include the library another way.
