### ISSUE TITLE
multiple condition in same series

### ISSUE THREAD

**Issue by mustafaevrenpolatford** [SiriDB/siridb-server#131]
I want to add more than one condition But I couldn't see any information in documantation.

For Example: 
select limit(1, mean) from "s01" between 1593179981s and 1593179996s **OR** between 1593179983s and 1593179998s

**Comment by joente** [comment]
@mustafaevrenpolatford , you can select series based on more than one condition but it is not possible (yet) to have multiple conditions based on the time range.

Do I understand it correctly that you want 2 points from the database? One for the average in the first time-window and one for the second?

**Comment by mustafaevrenpolatford** [comment]
@joente Yes, you got it right.

**Comment by joente** [comment]
I think that allowing multiple time ranges in a single query would only be a small speed improvement compared to use just two separate queries. SiriDB must find and load the data any way, and can only benefit from the series lookup as this only has to be done once. 
The code however, would really require a rather big design change since we currently only can handle a single *start* and single *end* time.
